#! /bin/sh
yum update -y
amazon-linux-extras install docker
service docker start
usermod -aG docker ec2-user
chkconfig docker on
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

http POST :3000/patients first_name="abdur" last_name=rahman email=kaziar42@gmail.com diagnosis=Cough image_url=https://profileimage.com
